nextApp:
  component: '@sls-next/serverless-component'
  inputs:
    cloudfront:
      distributionId: E2JDAKSJDZ2NR4
    domain: ['jdlennoxs.com']
    domainType: 'both'
    domainRedirects:
      jdlennoxs.com: https://www.jdlennoxs.com
    bucketName: jdlennoxs-site
    bucketRegion: eu-west-2
